name: MyNukkitPlugin
version: 1.0.0
author: aa1891256-commits
main: com.example.MyNukkitPlugin
commands:
  command1:
    description: Description of command1
    usage: /command1
  command2:
    description: Description of command2
    usage: /command2